---
docker_user: 'ja'

docker_deps:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'software-properties-common'
  - 'libffi-dev'
  - 'libssl-dev'
  - 'python3-dev'
  - 'python3'
  - 'python3-pip'
  - 'virtualenv'
  - 'python3-setuptools'
  - 'docker-compose'

docker_packages:
  - 'docker-ce'
  - 'docker-compose'