---

# https://dev.to/ymotongpoo/run-remote-install-scripts-without-using-curl-command-in-ansible-5b6b
- name: Download Docker
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/docker.sh

- name: Run Docker
  ansible.builtin.shell:
    cmd: cat /tmp/docker.sh | sh -s -- -y

- name: Include user into docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Reboot for changes to take effect
  reboot:

- name: Install prerequisites for docker-compose
  apt:
    pkg:
    - libffi-dev
    - libssl-dev
    - python3-dev
    - python3
    - python3-pip

- name: Install docker-compose
  pip:
    name: docker-compose

- name: Make sure docker service is running
  ansible.builtin.systemd:
    state: started
    name: docker