---

- name: Install required system packages
  package: 
    state: latest
    name: "{{ docker_deps }}"

- name: Update apt and install docker packages
  apt: 
    update_cache: yes 
    name: "{{ docker_packages }}"
    state: latest   

- name: Include user into docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Reboot for changes to take effect
  reboot:

- name: Make sure Docker is running and enabled
  service: 
    name: docker 
    state: started 
    enabled: yes