- hosts: [NewDNSServer]
  become: yes
  tasks:
    - name: Install Pi-hole
      include_role:
        name: chubchubsancho.pi_hole
      vars:
        pi_hole_dns_1: 127.0.0.1
        pi_hole_dns_1_port: 5335    

    - name: Remove Pi-hole password.
      ansible.builtin.shell:
        cmd: echo | pihole -a -p

    - name: Update repositories cache and install "Unbound" package
      apt:
        name: unbound
        update_cache: yes

    - name: Creating ja_unbound.conf file with content
      ansible.builtin.copy:
        src: ja_unbound.conf
        dest: /etc/unbound/unbound.conf.d/ja_unbound.conf

    - name: Restart service "Unbound" to update configuration
      ansible.builtin.service:
        name: unbound
        state: restarted