---
- name: Install beautiful soup python package
  ansible.builtin.shell: sudo apt install python3-*beautifulsoup*

- name: Install beautiful soup python package
  ansible.builtin.shell: sudo apt install python3-*bs4*

- name: Copy ini file
  copy:
    src: files/empleoPublico.ini.NOTFORGIT
    dest: /etc/scriptsJA/EmpleoPublico/empleoPublico.ini

- name: Program a job to find opportunities in the public sector
  cron:
    name: Check public employment opportunities
    minute: "2"
    hour: "9"
    job: "python3 /etc/scriptsJA/EmpleoPublico/empleoPublico.py > /dev/null"
    user: "{{ ansible_user }}"
