---
# https://www.jorgedelacruz.es/2019/07/22/en-busca-del-dashboard-perfecto-influxdb-telegraf-y-grafana-parte-xviii-monitorizar-temperatura-y-estado-de-raspberry-pi-4/

- name: Install Telegraf repository key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Install Telegraf repository
  apt_repository:
    repo: deb https://repos.influxdata.com/debian bullseye stable
    state: present

- name: Install Telegraf
  apt:
    name: telegraf
    state: latest
    update_cache: yes

- name: Start Telegraf
  service:
    name: telegraf
    state: started
    enabled: yes

- name: Copy config template to monitor Raspberry state
  template:
    src: templates/rpiservices.conf.j2
    dest: /etc/telegraf/telegraf.d/rpiservices.conf

- name: adding user 'telegraf' to group video
  user:
    name: telegraf
    groups: video
    append: yes

- name: Copy config file to get Raspberry temperature
  copy:
    src: files/raspberrypitemp.conf
    dest: /etc/telegraf/telegraf.d/raspberrypitemp.conf

- name: Restart service to apply new configuration
  service:
    name: telegraf
    state: restarted