---

- name: Add new user
  user:
      name={{ user }}
      # Password obtained with this command: 'mkpasswd --method=SHA-512'
      password={{ password }}
      shell="/bin/bash"

- name: Add user to the sudoers
  copy:
      dest: "/etc/sudoers.d/{{ user }}"
      content: "{{ user }}  ALL=(ALL)  NOPASSWD: ALL"

- name: Deploy SSH Key
  authorized_key: user={{ user }}
                  key="{{ lookup('file', '{{ ssh_key_file }}') }}"
                  state=present