---
- name: Add new user
  user:
      name={{ provision_user }}
      password={{ provision_password }}
      shell="/bin/bash"

- name: Add user to the sudoers
  copy:
      dest: "/etc/sudoers.d/{{ provision_user }}"
      content: "{{ provision_user }}  ALL=(ALL)  NOPASSWD: ALL"

- name: Deploy SSH Key
  authorized_key: user={{ provision_user }}
                  key="{{ lookup('file', '{{ provision_ssh_key_file }}') }}"
                  state=present