---

- name: Restart FileBrowser container
  community.docker.docker_container:
    name: filebrowser
    image: filebrowser/filebrowser:latest
    state: started
    restart_policy: always
    ports:
     - "8125:80"
    volumes:
     - "/:/srv"