---

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present
    update_cache: true

- name: Install required system packages
  package: 
    name: "{{ docker_deps }}"
    state: latest

- name: Update apt and install docker packages
  package: 
    name: "{{ docker_packages }}"
    state: latest   

- name: Include user into docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Reboot for changes to take effect
  reboot:

- name: Make sure Docker is running and enabled
  service: 
    name: docker 
    state: started 
    enabled: yes