---
# https://www.youtube.com/watch?v=X9fSMGkjtug
# https://dev.to/jacobhq/how-to-set-up-k3s-on-a-raspberry-pi-4-4343
# Uninstall K3S: https://rancher.com/docs/k3s/latest/en/installation/uninstall/

- hosts: [Kubernetes]
  gather_facts: no
  become: yes
  tasks:
    - import_tasks: tasks/prereq.yml

- hosts: [Master]
  gather_facts: no
  become: yes
  tasks:
    - name: Check if K3S is installed
      service:
        name: k3s
        state: started
      ignore_errors: yes
      register: k3s_present

    - name: Install K3S
      shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=“644” sh -s
      when: k3s_present.failed

    - name: Get Master token
      shell: sudo cat /var/lib/rancher/k3s/server/node-token
      register: master_token

    - name: "Add k3s token to dummy host"
      add_host:
        name: "K3S_TOKEN_HOLDER"
        token: "{{ master_token.stdout }}"

- hosts: [Nodes]
  gather_facts: no
  become: yes
  tasks:
    - name: Copy master token in nodes
      shell: curl -sfL https://get.k3s.io | K3S_TOKEN="{{ hostvars['K3S_TOKEN_HOLDER']['token'] }}" K3S_URL="https://{{ kubernetes_master }}:6443" K3S_NODE_NAME="{{ hostname }}" sh -
      register: master_token
