---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: "{{ docker_distro }}/gpg"
    state: present

- name: Get docker repository identifier
  shell: 'echo "deb [arch=$(dpkg --print-architecture)] {{ docker_distro }} $(lsb_release -cs) stable"'
  register: docker_repository
  changed_when: false

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_repository.stdout }}"
    state: present
    update_cache: true

- name: Install required system packages
  package:
    name: "{{ docker_deps }}"
    state: latest

- name: Update apt and install docker packages
  package:
    name: "{{ docker_packages }}"
    state: latest

- name: Include user into docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  register: user_group

- name: Reboot for changes to take effect
  reboot:
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: user_group.changed

- name: Make sure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
