---

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module
# https://github.com/notthebee/infra/blob/main/roles/homer/tasks/main.yml

- name: Restart Homer container
  community.docker.docker_container:
    name: homer
    image: b4bz/homer:latest
    state: started
    restart_policy: always
    ports:
     # Publish container port 8080 as host port 8902
     - "8902:8080"
    volumes:
     - "/portainer/Files/AppData/Config/Homer/assets:/www/assets"

- name: Template config.yml into server
  ansible.builtin.template:
    src: "{{role_path}}/templates/config.j2"
    dest: /portainer/Files/AppData/Config/Homer/assets/config.yml

- name: Copy and unzip icons into server
  ansible.builtin.unarchive:
    src: "{{role_path}}/files/icons.zip"
    dest: /portainer/Files/AppData/Config/Homer/assets/tools