---
- name: Check if Portainer is already running
  ansible.builtin.shell: sudo docker ps | grep portainer
  register: running_check
  ignore_errors: True
  changed_when: False

- name: Pull Portainer
  ansible.builtin.shell:
    cmd: sudo docker pull portainer/portainer-ce:latest
  when: "running_check.rc != 0"

- name: Run Portainer in Docker
  ansible.builtin.shell:
    cmd: sudo docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
  when: "running_check.rc != 0"