# Inspirado en https://github.com/derekfulmer/ansible/tree/main/roles/netplan
# La última tarea camiba la IP del SO y, por tanto, corta la conexión.
# Por ese motivo no se pueden añadir más tareas <--- IMPORTANTE

- hosts: [NewPiServers]
  become: yes
  
  vars_prompt:
    - name: "dns_server"
      prompt: "Seleccione el DNS a configurar (dns1 / dns2)"
      private: no
  
  tasks:
  - name: set array
    set_fact:
      source:
        dns1: 50-cloud-init-DNS1.yaml
        dns2: 50-cloud-init-DNS2.yaml

  - name: Copy the file
    copy:
      src: "{{ source[dns_server] }}"
      dest: /etc/netplan/50-cloud-init-kk.yaml
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Apply and reload the new static ip address with netplan
    command: netplan apply
    become: true
    async: 100
    poll: 0